// Code generated by MockGen. DO NOT EDIT.
// Source: gomock-shared-controller (interfaces: I)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=gomocksharedcontroller . I
//

// Package gomocksharedcontroller is a generated GoMock package.
package gomocksharedcontroller

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockI is a mock of I interface.
type MockI struct {
	ctrl     *gomock.Controller
	recorder *MockIMockRecorder
	isgomock struct{}
}

// MockIMockRecorder is the mock recorder for MockI.
type MockIMockRecorder struct {
	mock *MockI
}

// NewMockI creates a new mock instance.
func NewMockI(ctrl *gomock.Controller) *MockI {
	mock := &MockI{ctrl: ctrl}
	mock.recorder = &MockIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI) EXPECT() *MockIMockRecorder {
	return m.recorder
}

// M mocks base method.
func (m *MockI) M() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "M")
}

// M indicates an expected call of M.
func (mr *MockIMockRecorder) M() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "M", reflect.TypeOf((*MockI)(nil).M))
}
